# Site settings
title: IgniteSTEM
email: mdijkgraaf@princeton.edu
description: > # this means to ignore newlines until "baseurl:"
  Bring Hackathons, Maker Faires and Design Thinking to your students.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ignitestem.com" # the base hostname & protocol for your site
twitter_username: ignite_stem
facebook_username: igniteSTEM

# Build settings
markdown: kramdown

# Gems
plugins:
  - jekyll-sitemap

# Serve options
port: 5555
